### ISSUE TITLE
Package rhumsaa/uuid is abandoned

### ISSUE THREAD

**Issue by Roelwijnands** [antonioribeiro/tracker#102]
Hi,

I just installed the Tracker and already enjoy the lots off options that you have.
But when i installed it i get the error:
Package rhumsaa/uuid is abandoned, you should avoid using it. Use ramsey/uuid instead.

Might want to change your composer.json and move it to ramsey/uuid and test.

**Comment by ramsey** [comment]
Looks like this has been fixed in the `master` branch (yay!) but hasn't been released yet.

Until tracker releases what's in `master`, you may do the following in your project:

    composer require ramsey/uuid=^2.8

Since ramsey/uuid [indicates that it is a replacement for rhumsaa/uuid](https://github.com/ramsey/uuid/blob/36ebfcfc938e68f29345ea8931a788f8745f7663/composer.json#L53-L55), when Composer installs dependencies for tracker, it will use ramsey/uuid instead, and all will be well, and you won't see the warning message again. :-)

**Comment by antonioribeiro** [comment]
Fixed and released.
