### ISSUE TITLE
Migrations don't use "tracker" connection

### ISSUE THREAD

**Issue by jeanpaulvanbenthum** [antonioribeiro/tracker#107]
I configured the connection as specified in the docs, but the migration still uses the default connection. When u use the --database option for migrating it just migrates all the tables (including existing) to that connection.

Am i missing something here?

To make it work and use the "tracker" connection set in the config/tracker.php i made the following change. 

In the "pragmarx\support\src\Migration.php" file i changed line 189 in the checkConnection method to:

try {
	$this->connection = $this->manager->connection('tracker');
} catch (\InvalidArgumentException $e) {
	$this->connection = $this->manager->connection();
}

**Comment by AleksanderKoko** [comment]
Same thing here. When my main database was updated, I ended up with to much tables to handle

**Comment by antonioribeiro** [comment]
Fixed.

**Comment by tim-peterson** [comment]
Because there are so many Tracker tables, I separated them out into their own database. On the admin dashboard, it's unclear to me how to grab the `users` from my app's main database and yet grab page views from my Tracker database table. I'm getting a datatables.js error when I go the `http://localhost/stats?page=users` endpoint.  The user_ids are being stored in the `tracker_sessions`  table as expected but perhaps the Controller needs some re-working to switch between the two databases?

**Comment by tim-peterson** [comment]
The error I'm getting is localized on [L260](https://github.com/antonioribeiro/tracker/blob/master/src/Vendor/Laravel/Controllers/Stats.php#L260). 

I think it's because its trying to get user data on my Tracker database.
