### ISSUE TITLE
tracker_errors is not getting error code thus cannot track errors

### ISSUE THREAD

**Issue by potasiyam** [antonioribeiro/tracker#146]
I get this error when any 500 error occurs in my project.

> Error in exception handler: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'code' cannot be null (SQL: insert into `tracker_errors` (`message`,`code`, `updated_at`, `created_at`) values (Undefined variable: page, , 2016-01-31 12:09:32, 2016-01-31 12:09:32)) in F:\xampp2\htdocs\chorki-dev\vendor\laravel\framework\src\Illuminate\Database\Connection.php:625

So it seems tracker is unable to get the error code so db refuses to save it as the code column is not nullable.

**Comment by johndan102** [comment]
Hello, I am also having the same error. I am totally amiss about what step to take next. Can anyone kindly help?

**Comment by KeitelDOG** [comment]
I have the same problem too, it's my first day testing it.

If on development I suggest migrate:rollback, then modify the migration file on table tracker_error and add ->nullable() to column code : $table->string('code')->index()->nullable();

If on Production, rollback will delete the data, so simply create a new migration and change column code to nullable.
This shouldn't be the best approach, but this issue is being ignored since january 2016, so we have to make it happen.

**Comment by antonioribeiro** [comment]
Added a migration to help fixing this.
