### ISSUE TITLE
How can I modify default layouts?

### ISSUE THREAD

**Issue by netcan** [antonioribeiro/tracker#199]
I want to modify `vendor/pragmarx/tracker/src/views/index.blade.php`, but I ran ` php artisan vendor:publish --provider='PragmaRX\Tracker\Vendor\Laravel\ServiceProvider' --tag=view` didn't work.
How can I modify default layouts?

**Comment by alexandreMesle** [comment]
This package seems great, but it appears that the views are not publishable... 

The integration in a existing application would be far easier if one could publish some pages, I often wonder why so many packages do not make anything publishable (except the migrations of course)... For example, I would like to track the users that have multiple accounts, or the Ip adresses who try to make brute force attack. But nothing is publisheable... 

If one want to override the package default configuration, just create your own service provider as a subclass of the original service provider, and then you can change the view directory. I agree, it's an ugly hack... But as long as views are not published, we have no other choice left.

And good luck because it is a bit technical, but feasible. It is useless to add that rewriting the code in the vendor direcroty is definitely a bad idea.

**Comment by alexandreMesle** [comment]
When browsing the conf file, I found in line 361 of config/tracker.php the path of the layout view. 
`
    'stats_layout' => 'pragmarx/tracker::layout',
`
You can easily override it and it is by far a better solution than the awful hack suggested in my previous message.

**Comment by Perspective11** [comment]
@alexandreMesle Can you please give me an example of such change..
I copied the layout to my laravel views directory, but I wasn't able to point to the copied view..

**Comment by alexandreMesle** [comment]
@Perspective11 If you copied the layout file in your resources/views, you must replace 'pragmarx/tracker::layout' with the path of the copied (and therefore modified) layout.

**Comment by Perspective11** [comment]
Yes but in what format exactly
`./resources/views/tracker_layout` doesn't work
I tried a lot of formats

**Comment by alexandreMesle** [comment]
Have you tried to remove `./resource/views/` ?

**Comment by Perspective11** [comment]
Yes, it points to a relative directory inside the package files. real bummer...
