### ISSUE TITLE
Duplicate tracker agent name for FaceBook mobile app

### ISSUE THREAD

**Issue by tarekadam** [antonioribeiro/tracker#211]
Whenever somebody visits with Facebook mobile app, this happens.

Integrity constraint violation: 1062 Duplicate entry 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWeb' for key 'tracker_agents_name_unique'

(Most features in the config are set to on/true and we're using the middleware.)

**Comment by teepluss** [comment]
I have the same problem.

**Comment by DMeganoski** [comment]
I can verify, I am having this issue as well. Mine is slightly different. 

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWe' for key 'tracker_agents_name_unique' (SQL: insert into `tracker_agents` (`name`, `browser`, `browser_version`, `updated_at`, `created_at`) values (Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 [FBAN/FBIOS;FBAV/68.0.0.49.70;FBBV/41924288;FBRV/0;FBDV/iPhone8,1;FBMD/iPhone;FBSN/iOS;FBSV/10.0.2;FBSS/2;FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5], Facebook, 68.0.0, 2016-11-19 17:31:48, 2016-11-19 17:31:48))
```

I have implemented this package in a application targeted at mobile devices and social networks. This is a big issue for me. I'm working on trying to track down why this is happening.

**Comment by DMeganoski** [comment]
Figured it out, was what I suspected all along. The column type is varchar 255, and the string that is generated for the name column on the Facebook app for iPhone is too long to fit into the column.

So, when it tries to match the string it gets no results, because the stored value is truncated. Then, when it goes to save it again, the value is again truncated and why we get this error.

This can be fixed by either increasing the column length or changing the type to text. Note that the unique index on this column will not allow for a text column or varchar with a length greater than 255, so in order to fix this, you will have to remove the index from it as well.

Here is my migration file which solved this issue.

```php
public function up() {
        Schema::table('tracker_agents', function ($table) {
            $table->dropUnique('tracker_agents_name_unique');
        });
        
        Schema::table('tracker_agents', function($table) {
            $table->mediumText('name')->change();
        });
    }
    
    public function down() {
        Schema::table('tracker_agents', function ($table) {
            $table->string('name', 255)->change();
            $table->unique('name');
        });
    }
```

**Comment by antonioribeiro** [comment]
Created a migration to fix it. Thank you!

https://github.com/antonioribeiro/tracker/commit/1e8b7043961b8b36c017a8443ba72472215e6e13
