### ISSUE TITLE
Can't Migrate 5.4

### ISSUE THREAD

**Issue by anyadvisor** [antonioribeiro/tracker#294]
When I run

php artisan:migrate

I get the following error:

```

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' (SQL: create table `
  aa_tracker_paths` (`id` bigint unsigned not null auto_increment primary key, `path` varchar(191) not null, `created
  _at` timestamp not null, `updated_at` timestamp not null) default character set utf8mb4 collate utf8mb4_unicode_ci)
   (SQL: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' (SQL: create
  table `aa_tracker_paths` (`id` bigint unsigned not null auto_increment primary key, `path` varchar(191) not null, `
  created_at` timestamp not null, `updated_at` timestamp not null) default character set utf8mb4 collate utf8mb4_unic
  ode_ci))



  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' (SQL: create table `
  aa_tracker_paths` (`id` bigint unsigned not null auto_increment primary key, `path` varchar(191) not null, `created
  _at` timestamp not null, `updated_at` timestamp not null) default character set utf8mb4 collate utf8mb4_unicode_ci)



  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at'
```

If I change all of the timestamp('created_at')->index(); to just timestamps() then it mostly works, it creates the tables at least, but this is obviously not ideal

Is this not suitable for Laravel 5.4?

**Comment by metinbulak** [comment]
hi
Can you upload sql file  here, I can not create  tables.

**Comment by amylashley** [comment]
I'm having this same issue.

**Comment by antonioribeiro** [comment]
This is something working for many people and for ages. This is probably related to MySQL, which I don't use much, but was used to test this last version. But since you are having trouble with some very old migrations, it should be related to your SQL modes:

https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at

The difference between Laravel's timestamps() and tracker's timestamps is the absent 'nullable()', which makes no sense on a table which will always have them filled and are used as index.

So, my advice is to change your Laravel database configuration to 

    'strict' => false,

Strict usually defaults to true and this is what it sets on your MySQL:

```
set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
```

**Comment by amylashley** [comment]
@antonioribeiro this seems to work for me. I added this to my "tracker" db connection and left the default connection as is. Thank you!

**Comment by antonioribeiro** [comment]
Thanks for the feedback. Added a troubleshooting section to the docs: https://github.com/antonioribeiro/tracker#troubleshooting
