### ISSUE TITLE
method edit_column

### ISSUE THREAD

**Issue by jonquintero** [antonioribeiro/tracker#431]
Hi, could you fix this error on datable: **method edit_column not exist** ? the right name is **editColumn**

**Comment by jonquintero** [comment]
en add_column the name es **addColumn**

**Comment by jonquintero** [comment]
all this in case of use yajra/laravel-datatables

**Comment by meliani** [comment]
I'm experiencing the same problem months ago, tried to replace edit_column/add_column by editColumn/addColumn but it doesent solve the problem, please tell us if tracker doesn't support newer versions of yajra/laravel-datatables

**Comment by drbyte** [comment]
> I'm experiencing the same problem months ago, tried to replace edit_column/add_column by editColumn/addColumn but it doesent solve the problem, please tell us if tracker doesn't support newer versions of yajra/laravel-datatables

It doesn't support `yajra datatables` at all. It uses `Bllim/Datatables` instead:

https://github.com/antonioribeiro/tracker/blob/7c4e6dacafcebb26632eed7d7dbcab727c3deac6/src/Vendor/Laravel/ServiceProvider.php#L568-L573

**Comment by nasirkhan** [comment]
is there any workaround for the `yajra datatables` users like me?

**Comment by drbyte** [comment]
I haven't tried it yet, but since this package aggressively forces its own use of the `Datatable` facade, you could manually tell the Arjay package to register its facade under a different name ... and then update all your code to use the renamed facade.

In the meantime, I just find that since this package isn't merging PRs or fixing bugs I'm just not using it. It's a shame because it seems to do the most thorough collection of data.

**Comment by antonioribeiro** [comment]
Fixed.
