### ISSUE TITLE
Same uuid for different user of same device

### ISSUE THREAD

**Issue by pranshu792** [antonioribeiro/tracker#72]
![capture](https://cloud.githubusercontent.com/assets/8383179/6664029/f7804508-cbf1-11e4-8de1-c57629ceb1ea.PNG)

User ID has been replaced with the current user, if both users logged in from same device. Thus, No unique UUID has been created. All the logs for previous user_id will be credited to current user_id.

In my case, See Updated at. This is the timestamp when only user_id is replaced.

**Comment by antonioribeiro** [comment]
This is a problem I don't really know how to fix without some kind of hack. I'm currently using PHP session to control the user session because Laravel's sessions changes way more frenquently whan we would like in a system that is supposed to track all user's steps. 

A simple example is, if a user is browsing your site for, let's say 10 minutes and then she decides to register and login, Laravel's session id will change after login and you loose track of all things she did on your site before login.

Laravel tries to keep the session data, so we could just store a session id in Laravel's session, right? Maybe, I had trouble doing that too in Laravel 5, and in Laravel 5 is "worse" because session data is loaded via a middleware and when a service provider is booted is may not have access to the session data yet. I would probably have to create a middleware and ask Tracker's users to add that middleware to their application's, one step more to install a package people are already having pain to install.

My best bet is to change our internal session id everytime a user changes, but I'm not sure this is a good option, so I'm open to suggestions.

**Comment by pranshu792** [comment]
You can create a first or new row for a token and user_id in tracker_sessions table, By this different row will be created for different user with same uuid token..!

**Comment by antonioribeiro** [comment]
Should be fixed on master now.

**Comment by gaupoit** [comment]
Have you already fixed in version 2.0@dev? I still see the above issue in my application.
